verify_signatures: false

PreCommit:
  ALL:
    on_fail: warn
    on_warn: warn # Treat all warnings as failures

  RuboCop:
    enabled: true
    
  Fasterer:
    enabled: true

  JsHint:
    enabled: true

  AuthorName:
    enabled: false
    
CommitMsg:
  ALL:
    quiet: true
