AllCops:
  Exclude:
    - 'spec/**/*'
    - 'db/schema.rb'
  TargetRubyVersion: 2.3.1
  DisplayCopNames: true

FrozenStringLiteralComment:
  Enabled: false

Documentation:
  Enabled: false

TrailingBlankLines:
  Enabled: false

Style/StringLiterals:
  Enabled: false  

Rails:
  Enabled: true

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false
